imports:
    - { resource: tables.yml }

services:
    drdeath.f1webtip.controller:
        class: drdeath\f1webtip\controller\main
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@log'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
    drdeath.f1webtip.listener:
        class: drdeath\f1webtip\event\main_listener
        arguments:
            - '%core.php_ext%'
            - '@service_container'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@template'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
    drdeath.f1webtip.cron.task.email_reminder:
        class: drdeath\f1webtip\cron\task\email_reminder
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@log'
            - '@user'
            - '@language'
        calls:
            - [set_name, [drdeath.f1webtip.cron.task.email_reminder]]
        tags:
            - { name: cron.task }
