imports:
    - { resource: tables.yml }

services:
    drdeath.f1webtip.controller:
        class: drdeath\f1webtip\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    drdeath.f1webtip.listener:
        class: drdeath\f1webtip\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
    cron.task.core.email_reminder:
        class: drdeath\f1webtip\cron\task\core\email_reminder
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
        calls:
            - [set_name, [cron.task.core.email_reminder]]
        tags:
            - { name: cron.task }
