parameters:
    tables.f1webtip.drivers: '%core.table_prefix%f1webtip_drivers'
    tables.f1webtip.teams: '%core.table_prefix%f1webtip_teams'
    tables.f1webtip.races: '%core.table_prefix%f1webtip_races'
    tables.f1webtip.wm: '%core.table_prefix%f1webtip_wm'
    tables.f1webtip.tips: '%core.table_prefix%f1webtip_tips'
